apiVersion: apps/v1
kind: Deployment

metadata:
  name: self-healing-app
  namespace: devops-platform

spec:
  replicas: 1

  selector:
    matchLabels:
      app: self-healing-app

  template:
    metadata:
      labels:
        app: self-healing-app

    spec:
      containers:
      - name: self-healing-app

        image: sne16/self-healing-app:latest

        imagePullPolicy: Always

        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT

        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_VERSION

        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: API_KEY

        volumeMounts:
        - name: app-storage
          mountPath: /data

        ports:
        - containerPort: 5000

        readinessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 15
          periodSeconds: 20

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "200m"
            memory: "256Mi"

      volumes:
        - name: app-storage

          persistentVolumeClaim:
            claimName: app-pvc