apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace: devops-platform

spec:
  selector:
    app: self-healing-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort