apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: app-pvc
  namespace: devops-platform

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi